# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.4
  - 1.5
#  - nightly

matrix:
  allow_failures:
    - julia: 1.5
    - julia: nightly

addons:
    apt: # apt-get for linux
        packages:
          - libnetcdf-dev

notifications:
  email: false

# using default test script
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("DIVAndNN")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("DIVAndNN")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.build("DIVAndNN")'
        - julia --project=docs/ docs/make.jl
      after_success: skip
